#!/usr/bin/env python3
"""
Rasterise the Night's Watch mark into the PNG sizes the page and the social
cards need. src/static/mark.svg is the source of truth; this reproduces the same
geometry analytically, because there is no SVG rasteriser on this machine and
adding a dependency for two square images is not a trade worth making.

    python3 scripts/make-mark.py

Writes src/static/mark.png (96px, header and favicon fallback) and
src/static/logo.png (512px, og:image and apple-touch-icon only). Standard
library only.
"""

import struct
import zlib
from pathlib import Path

GROUND = (0x17, 0x16, 0x14)   # --bg,     unlit wood
STAR   = (0xcd, 0x85, 0x60)   # --rust,   the lit thing
WALL   = (0x8b, 0xb8, 0xdc)   # --accent, the structure
SS = 4                        # supersampling per axis

# Eight-pointed star, alternating long and short radii about a centre that sits
# above the wall. Computed rather than hand-listed so the SVG and the PNGs cannot
# drift apart: make_svg() below emits the same points.
import math

STAR_CX, STAR_CY = 32.0, 25.0
STAR_R_OUT, STAR_R_IN = 17.0, 6.6

STAR_PTS = []
for i in range(16):
    ang = -math.pi / 2 + i * math.pi / 8          # start pointing up
    r = STAR_R_OUT if i % 2 == 0 else STAR_R_IN
    STAR_PTS.append((STAR_CX + r * math.cos(ang), STAR_CY + r * math.sin(ang)))

# Crenellated wall: five merlons, solid below, clipped by the roundel. The wall is
# drawn over the star, so the star must not reach below the merlon tops or its rays
# show through the gaps.
MERLONS = 5
WALL_TOP, MERLON_TOP, WALL_BOT = 46.0, 41.5, 60.0
WALL_L, WALL_R = 9.0, 55.0

def _wall_points():
    pts = [(WALL_L, WALL_TOP)]
    span = (WALL_R - WALL_L) / (MERLONS * 2 - 1)
    x = WALL_L
    for i in range(MERLONS * 2 - 1):
        nxt = x + span
        # Merlons rise to MERLON_TOP, embrasures drop back to WALL_TOP. Both
        # segments must be emitted or the outline is a flat slab.
        top = MERLON_TOP if i % 2 == 0 else WALL_TOP
        pts += [(x, top), (nxt, top)]
        x = nxt
    pts += [(WALL_R, WALL_TOP), (WALL_R, WALL_BOT), (WALL_L, WALL_BOT)]
    return pts

WALL_PTS = _wall_points()


def in_poly(x, y, pts):
    """Even-odd point-in-polygon. Good enough: neither shape self-overlaps."""
    inside = False
    n = len(pts)
    for i in range(n):
        x1, y1 = pts[i]
        x2, y2 = pts[(i + 1) % n]
        if (y1 > y) != (y2 > y):
            xin = x1 + (y - y1) / (y2 - y1) * (x2 - x1)
            if x < xin:
                inside = not inside
    return inside


def sample(ux, uy):
    """Colour at a point in SVG units, or None outside the roundel."""
    dx, dy = ux - 32, uy - 32
    if dx * dx + dy * dy > 32 * 32:
        return None
    if in_poly(ux, uy, STAR_PTS):
        return STAR
    if in_poly(ux, uy, WALL_PTS):
        return WALL
    return GROUND


def png_bytes(size):
    scale = 64.0 / size
    raw = bytearray()
    for y in range(size):
        raw.append(0)                                   # filter type 0
        for x in range(size):
            r = g = b = a = 0
            hits = 0
            for sy in range(SS):
                for sx in range(SS):
                    c = sample((x + (sx + 0.5) / SS) * scale,
                               (y + (sy + 0.5) / SS) * scale)
                    if c is None:
                        continue
                    hits += 1
                    r += c[0]; g += c[1]; b += c[2]
            total = SS * SS
            if hits == 0:
                raw += bytes((0, 0, 0, 0))
                continue
            a = int(round(255 * hits / total))
            raw += bytes((r // hits, g // hits, b // hits, a))

    def chunk(tag, data):
        return (struct.pack('>I', len(data)) + tag + data
                + struct.pack('>I', zlib.crc32(tag + data) & 0xffffffff))

    ihdr = struct.pack('>IIBBBBB', size, size, 8, 6, 0, 0, 0)   # 8-bit RGBA
    return (b'\x89PNG\r\n\x1a\n'
            + chunk(b'IHDR', ihdr)
            + chunk(b'IDAT', zlib.compress(bytes(raw), 9))
            + chunk(b'IEND', b''))


def make_svg(roundel=True):
    """With the roundel for the favicon and the social card, where the mark needs
    its own ground. Without it for the header and footer, where a hard dark disc
    on a light page reads as a blob rather than a sigil."""
    def path(pts):
        return 'M' + ' L'.join(f'{x:.2f} {y:.2f}' for x, y in pts) + ' Z'
    ground = '  <circle cx="32" cy="32" r="32" fill="#171614"/>\n' if roundel else ''
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img"'
        ' aria-label="The Night\'s Watch">\n'
        "  <!-- An eight-pointed star standing over a battlement: the fire kept\n"
        "       burning on the wall. GENERATED by scripts/make-mark.py - do not\n"
        "       hand-edit, run the script. The star is terracotta because it is the\n"
        "       lit thing; the wall is slate because it is the structure. -->\n"
        + ground +
        f'  <path fill="#cd8560" d="{path(STAR_PTS)}"/>\n'
        f'  <path fill="#8bb8dc" d="{path(WALL_PTS)}"/>\n'
        '</svg>\n'
    )


def main():
    out = Path(__file__).resolve().parent.parent / 'src' / 'static'
    (out / 'mark.svg').write_text(make_svg())
    print(f'{"mark.svg":14} vector, roundel   {len(make_svg()):>7} bytes')
    inline = make_svg(roundel=False)
    (out / 'mark-inline.svg').write_text(inline)
    print(f'{"mark-inline.svg":14} vector, bare      {len(inline):>7} bytes')
    for name, size in (('mark.png', 96), ('logo.png', 512)):
        data = png_bytes(size)
        (out / name).write_bytes(data)
        print(f'{name:10} {size}x{size}  {len(data):>7} bytes')


if __name__ == '__main__':
    main()
